package com.exavalu.customer.product.portal.entities.dto.orderFeedbackDetails;

//@JsonDeserialize(using = OrderDetailsDeserializer.class) 

import com.fasterxml.jackson.annotation.JsonProperty;

public class OrderDetailsRequest {
	@JsonProperty("orderId")
	private String orderId;

	@JsonProperty("feedback")
	private FeedbackDetails feedback;

	// Getters and setters (generated by Lombok or manually)
	public String getOrderId() {
		return orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public FeedbackDetails getFeedback() {
		return feedback;
	}

	public void setFeedback(FeedbackDetails feedback) {
		this.feedback = feedback;
	}

	@Override
	public String toString() {
		return "OrderDetailsRequest{" + "orderId='" + orderId + '\'' + ", feedback=" + feedback + '}';
	}
}